### ISSUE TITLE
Есть проблема не к этому моду

### ISSUE THREAD

**Issue by Ochpochmaks** [floppa-coder/IronExtened#3]
Как сделать так, чтобы мод появился в Mindustry? Я уже добавил всё что есть, остаётся только чтобы мод появился в Mindustry, лисенс с реад ми добавлены, если знаешь в чём проблема ответь, пожалуйста, когда сможешь.

**Comment by floppa-coder** [comment]
Добавь теги mindustry-mod, mindustry-mod-v7, mindustry-mods и mindustry

**Comment by floppa-coder** [comment]
а, ещё, ПИШИ КУДА УГОДНО, НО НЕ СЮДА...
